INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 118, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py", line 99, in divide
    right_subgraph.remove_edge(node_id, neighbors[1])
                                        ~~~~~~~~~^^^
IndexError: list index out of range
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/fuse/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 68, in fuse
    if point1_id not in LineStringHandler_instance.graphs[point1_source].find_end_nodes() :
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'fa97ab51-348a-42dd-81c4-14abeba689d5'
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/fuse/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 68, in fuse
    if point1_id not in LineStringHandler_instance.graphs[point1_source].find_end_nodes() :
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'f6e5280f-9524-4e47-9fd9-b5a5bff9a835'
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: 'divided-fbd4f7'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: 'divided-05ea15'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-05ea15'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 122, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-157ead'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-157ead'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-157ead'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-157ead'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-157ead'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 120, in divide
    self.remFeature(point_source)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 80, in remFeature
    self.features.pop(featureId)
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-4cc0a0'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'divided-4cc0a0'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'f6e5280f-9524-4e47-9fd9-b5a5bff9a835'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 94, in divide
    LineStringHandler_instance.divide(point_source, point_id)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py", line 102, in divide
    left_graph,right_graph = self.graphs[point_source].divide(point_id)
                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 92, in divide
    if point_id not in LineStringHandler_instance.graphs[point_source].nodes():
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: '2ecfd4c2-1167-41b0-89f3-a2731c53bded'
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /map/divide/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view map.views.divide didn't return an HttpResponse object. It returned None instead.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\urls.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /map/map/getTLMSimpleFeatures/
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /map/map/getTLMSimpleFeatures/
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/getTLMSimpleFeatures/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 13, in getTLMSimpleFeatures
    if request.methode == 'POST' :
       ^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'methode'
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /map/getTLMSimpleFeatures/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 13, in getTLMSimpleFeatures
    if request.methode == 'GET' :
       ^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'methode'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /map/getTLMSimpleFeatures/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 13, in getTLMSimpleFeatures
    if request.methode == 'GET' :
       ^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'methode'
ERROR:django.request:Internal Server Error: /map/getTLMSimpleFeatures/
Traceback (most recent call last):
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py", line 13, in getTLMSimpleFeatures
    if request.methode == 'GET' :
       ^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'methode'
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\mapFunction.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:C:\Users\gerth\ITV Consult AG\itvdata - 3_Geschaeft\33_Projekte\BAZL\7000_DCS\5 - Operation\Tools\Python Script DCS\HL Read Find Format\NEW\PowerlineTool\map\lineString.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
